//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCEnvanter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PCEnvanter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZHAOXIN KaiXian ZX-C+ C4700@2.0GHz	1,547	2521	NA	NA
        ///ZHAOXIN KaiXian KX-U6780A@2.7GHz	3,831	1530	NA	NA
        ///ZHAOXIN KaiXian KX-U6580@2.5GHz	3,227	1694	NA	NA
        ///ZHAOXIN KaiXian KX-6640MA@2.2+GHz	1,549	2518	NA	NA
        ///Vili based on Qualcomm Technologies, Inc SM8350	5,299	1269	NA	NA
        ///VIA QuadCore U4650 @ 1.0+ GHz	666	3304	NA	NA
        ///VIA QuadCore L4700 @ 1.2+ GHz	773	3179	NA	NA
        ///VIA QuadCore C4650@2.0GHz	1,352	2654	NA	NA
        ///VIA Nehemiah	101	3971	NA	NA
        ///VIA Nano X2 U4025 @ 1.2 GHz	393	3587	NA	NA
        ///VIA Nano U3500@1000MHz	184	3869 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cpuData {
            get {
                return ResourceManager.GetString("cpuData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1TB PCS 2.5&quot; SSD	953.9 GB	3,745	3366	NA	NA
        ///1TB PCS PCIe M.2 SSD	953.9 GB	14,974	1078	NA	NA
        ///1TB QLC SSD	953.9 GB	3,594	3606	NA	NA
        ///2-Power SSD2041A 120GB	111.8 GB	3,605	3587	NA	NA
        ///2-Power SSD2042A 240GB	223.6 GB	3,515	3770	NA	NA
        ///2-Power SSD2042B 256GB	238.5 GB	3,186	4362	NA	NA
        ///2-Power SSD2043A 480GB	447.1 GB	2,598	5336	NA	NA
        ///2-Power SSD2043B 512GB	476.9 GB	4,553	2324	NA	NA
        ///3Q SSD S220-64GB	55.9 GB	1,816	6115	NA	NA
        ///3Q SSD S220-128GB	111.8 GB	2,156	5865	NA	NA
        ///30TT253X2-512GB	476.9 GB	2,533	5416	NA	NA        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hddData {
            get {
                return ResourceManager.GetString("hddData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Yeni bir liste hazırlamak için:
        ///	* Dosya-&gt;Yeni-&gt;Pc Listesi Hazırlayı seçin
        ///	* Gelen ekranda hangi adla başlayan bilgisayarları aratmak istiyorsanız bunları ; ile ayırarak girin.
        ///	* Yeşil Göstergenin dolmaya çok yakınken işlemi bitmiş kabul edebilirsiniz.
        ///	  bekleme gerekçesi artık var olmayan bilgisayarlarıda sorgulaması.
        ///
        ///-Bir Listeyi kaydetmek için:
        ///	* Bir liste Açın
        ///	* Dosya-&gt;Kaydeti seçin 
        ///
        ///-Kayıtlı Listeyi Açmak için:
        ///	* Dosya-&gt;Aç-&gt;Pc Listeyi seçin
        ///	* Gelen ekranda &quot;json&quot; uzantı kayıt dosy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string kk {
            get {
                return ResourceManager.GetString("kk", resourceCulture);
            }
        }
    }
}
